server:
  port: 8888
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s

management:
  endpoints:
    web:
      exposure:
        include: refresh

spring:
  application:
    name: config-service
  profiles:
    active: native
  lifecycle:
    timeout-per-shutdown-phase: 10s
  cloud:
    config:
      server:
        native:
          search-locations: file:${CONFIG_SEARCH_LOCATIONS:../env}
          fail-on-error: true
  rabbitmq:
    username: user
    password: password
    host: localhost
    port: 5672

app:
  refresh:
    exchange: config.topic
    routing-key: config.env.refresh
#        git:
#          uri: https://github.com/PolarBookshop/config-repo
#          default-label: main
#          timeout: 5
#          clone-on-start: true
#          force-pull: true
